### PR TITLE
fix Chinese translation

### PR DESCRIPTION
**Pull request by kaizhi-singtown**

### CODE REVIEW

**Comment by kwagyeman** [comment]
Hi, can you do this? Download qtlinguist and then open up the .ts file and then change the string using that file.

**Comment by kwagyeman** [comment]
@kidswong999 Please edit the qtlinguist files using qtlinguist (the .tx files). The PO files are not the input for translation anymore.

**Comment by kaizhi-singtown** [comment]
@kwagyeman I edited the ts file.

**Review by kwagyeman — APPROVED** [review]

**Comment by kwagyeman** [comment]
Can't merge this anymore. Too old. I am sorry.

**Pull request closed without merging**
