### PR TITLE
Update black_grayscale_line_following.py

### PR DESCRIPTION
**Pull request by seth10**

### CODE REVIEW

**Comment by kwagyeman** [comment]
Can you send your PR to the OpenMV repo? The example scripts here are mirrors of what's in that repo.

**Comment by seth10** [comment]
@kwagyeman Ah, I was looking in the openmv-ide repo (because I found this example in the IDE) and couldn't find it there. Got it, thanks for pointing [it](https://github.com/openmv/openmv/blob/master/usr/examples/10-Color-Tracking/black_grayscale_line_following.py) out!

**Comment by kwagyeman** [comment]
Ibrahim likes one commit per PR. Squash your commits.

For the IDE repo I don't care, but, for the openmv you have to follow Ibrahim's rules.

Sent from my Verizon Wireless 4G LTE Droid
On May 23, 2017 8:51 AM, Seth T <notifications@github.com> wrote:

@kwagyeman<https://github.com/kwagyeman> Ah, I was looking in the openmv-ide repo (because I found this example in the IDE) and couldn't find it there. Got it, thanks for pointing it<https://github.com/openmv/openmv/blob/master/usr/examples/10-Color-Tracking/black_grayscale_line_following.py> out!

**Comment by seth10** [comment]
OK! Do you see an option "Squash and marge"?
squashandmerge

**Comment by kwagyeman** [comment]
Already merged.

Sent from my Verizon Wireless 4G LTE Droid
On May 23, 2017 11:57 AM, Seth T <notifications@github.com> wrote:

OK! Do you see an option "Squash and marge"?
[squashandmerge]<https://cloud.githubusercontent.com/assets/5026621/26371241/29792b78-3fc8-11e7-9e08-82f447f09380.PNG>

**Comment by seth10** [comment]
Oh, great :D

**Pull request merged**
