### PR TITLE
Add script to fetch IDE data for packaging.

### PR DESCRIPTION
**Pull request by iabdalkader**

### CODE REVIEW

**Comment by Slavjan** [comment]
Is it possible to somehow connect your features to the original QtC?

**Comment by kwagyeman** [comment]
What features do you want? I've explicitly hidden things in the IDE to make it more streamlined. However, I can re-enable them if needed.

**Comment by Slavjan** [comment]
I want to programming OpenMV Cam7 with original QtCreator, how I cam config. this?

**Comment by kwagyeman** [comment]
Ho, there's no way to do this right now. That said, you can edit scripts in another editor and OpenMV IDE will detect the script being changed externally and reload the script.

**Comment by kwagyeman** [comment]
Added manually

**Pull request closed without merging**
